# Generated by Django 3.2.25 on 2025-04-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20250428_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='admin_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
