# Generated by Django 3.2.25 on 2025-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('x_handle', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedIn', models.URLField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
