# Generated by Django 3.2.25 on 2025-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myinfo',
            options={'verbose_name_plural': 'MyInfo'},
        ),
        migrations.RenameField(
            model_name='myinfo',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='myinfo',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='facebook',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='instagram',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='x_handle',
            field=models.URLField(max_length=100),
        ),
    ]
