# Generated by Django 3.2.25 on 2025-04-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_myinfo_my_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('service_image', models.ImageField(upload_to='service/')),
                ('service_box_description', models.TextField()),
                ('service_description', models.TextField()),
                ('service_body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='My_img/'),
        ),
    ]
