# Generated by Django 3.2.25 on 2025-04-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_auto_20250415_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='brief_description',
        ),
    ]
