# Generated by Django 3.2.25 on 2025-04-24 03:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_auto_20250416_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='', verbose_name='details/')),
                ('image2', models.ImageField(upload_to='', verbose_name='details/')),
                ('image3', models.ImageField(upload_to='', verbose_name='details/')),
                ('image4', models.ImageField(upload_to='', verbose_name='details/')),
                ('client', models.CharField(max_length=100)),
                ('project_date', models.CharField(max_length=20)),
                ('project_url', models.URLField(max_length=100)),
                ('project_title', ckeditor.fields.RichTextField()),
                ('project_description', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myportfolio.projectcategory')),
            ],
        ),
    ]
