# Generated by Django 3.2.25 on 2025-04-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_portfoliodetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliodetails',
            options={'verbose_name_plural': 'PortfolioDetails'},
        ),
    ]
