# Generated by Django 3.2.25 on 2025-04-24 08:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_alter_portfoliodetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetails',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='', verbose_name='details/')),
                ('image2', models.ImageField(upload_to='', verbose_name='details/')),
                ('image3', models.ImageField(upload_to='', verbose_name='details/')),
                ('image4', models.ImageField(upload_to='', verbose_name='details/')),
                ('client', models.CharField(max_length=100)),
                ('project_date', models.CharField(max_length=20)),
                ('project_url', models.URLField(max_length=100)),
                ('project_title', ckeditor.fields.RichTextField()),
                ('project_description', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myportfolio.projectcategory')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
