# Generated by Django 3.2.25 on 2025-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_auto_20250424_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='image1',
            field=models.ImageField(upload_to='details/'),
        ),
        migrations.AlterField(
            model_name='projectportfolio',
            name='image2',
            field=models.ImageField(upload_to='details/'),
        ),
        migrations.AlterField(
            model_name='projectportfolio',
            name='image3',
            field=models.ImageField(upload_to='details/'),
        ),
        migrations.AlterField(
            model_name='projectportfolio',
            name='image4',
            field=models.ImageField(upload_to='details/'),
        ),
    ]
